/**
 * Domain 3: Curated Question Pool & Dynamic Requirement Binder
 * Houses vetted, gold-standard interview question templates across core competencies.
 * Dynamically binds requirement IDs (r1..rn) at runtime to reduce LLM latency and costs
 * while strictly guaranteeing referential integrity and Appendix A compliance.
 */
import { Requirement, Question, genQIds } from '@taro/shared';

export interface CuratedQuestionTemplate {
  category: 'technical' | 'behavioural' | 'system-design' | 'company-fit';
  tags: string[];
  prompt: string;
  answer_outline: string;
  evaluation_criteria: string[];
  difficulty: 1 | 2 | 3;
}

/**
 * 25+ High-Yield Curated Question Templates covering foundational engineering
 * and behavioral leadership competencies.
 */
export const CURATED_QUESTION_TEMPLATES: CuratedQuestionTemplate[] = [
  // ── Data Structures & Algorithms ──────────────────────────────────────────
  {
    category: 'technical',
    tags: ['dsa', 'data structures', 'algorithms', 'arrays', 'hash', 'strings', 'two pointer'],
    prompt: 'How would you find the longest substring without repeating characters in O(n) time and O(min(m,n)) space?',
    answer_outline:
      'Use a sliding window with a HashMap storing each character and its last seen index. Expand the right pointer; when a duplicate is encountered inside the current window, jump the left pointer past the previous occurrence.',
    evaluation_criteria: [
      'Correctly identifies sliding window technique with dynamic left/right pointers',
      'Explains O(n) time complexity and O(min(m,n)) character set space bounds',
      'Handles edge cases (empty strings, all identical characters)',
    ],
    difficulty: 2,
  },
  {
    category: 'technical',
    tags: ['dsa', 'data structures', 'algorithms', 'trees', 'graphs', 'bfs', 'dfs'],
    prompt: 'Compare Breadth-First Search (BFS) and Depth-First Search (DFS) in graph traversal. In which scenarios is BFS preferred?',
    answer_outline:
      'BFS explores level-by-level using a queue, finding the shortest path in unweighted graphs. DFS explores deep along branches using a stack or recursion, ideal for topological sort, cycle detection, and maze solving.',
    evaluation_criteria: [
      'Contrasts queue-based vs recursion/stack-based state management',
      'Cites BFS shortest-path guarantee on unweighted edges',
      'Explains memory consumption: BFS width vs DFS branch depth',
    ],
    difficulty: 2,
  },

  // ── Distributed Systems & Microservices ───────────────────────────────────
  {
    category: 'technical',
    tags: ['microservices', 'distributed systems', 'architecture', 'scalability', 'system design', 'high-throughput'],
    prompt: 'How do you design an idempotent API endpoint for payment processing or state mutations in a distributed system?',
    answer_outline:
      'Require an Idempotency-Key in the HTTP header generated by the client (e.g. UUID v4). Before processing, acquire a distributed lock in Redis or insert into an idempotency table with status PENDING. If already processed, return the cached result payload without re-executing business logic.',
    evaluation_criteria: [
      'Explains Idempotency-Key header mechanism and unique UUID tracking',
      'Discusses concurrency race condition handling (atomic set-if-not-exists or DB unique index)',
      'Distinguishes in-flight deduplication from completed response caching',
    ],
    difficulty: 3,
  },
  {
    category: 'technical',
    tags: ['distributed systems', 'consistency', 'cap', 'partition', 'database', 'eventual consistency'],
    prompt: 'Explain the CAP theorem and the trade-offs between CP and AP distributed data stores during a network partition.',
    answer_outline:
      'Under a network partition (P), a distributed system must choose between Consistency (all nodes return the latest write, sacrificing availability by returning errors) or Availability (every request receives a response, but data may be stale).',
    evaluation_criteria: [
      'Correctly emphasizes that partitions (P) are unavoidable in distributed networks',
      'Explains CP behavior (e.g. Raft consensus rejecting writes when quorum is lost)',
      'Explains AP behavior (e.g. DynamoDB/Cassandra accepting writes with eventual convergence)',
    ],
    difficulty: 2,
  },

  // ── Caching & Redis ───────────────────────────────────────────────────────
  {
    category: 'technical',
    tags: ['redis', 'caching', 'cache', 'cache invalidation', 'key-value', 'memcached', 'latency'],
    prompt: 'What are the main cache invalidation strategies (e.g., Cache-Aside, Write-Through, Write-Behind), and how do you prevent cache stampedes (thundering herd)?',
    answer_outline:
      'Cache-Aside queries cache first, reads from DB on miss, and writes back. Write-Through updates cache and DB synchronously. To prevent cache stampedes on TTL expiry, use probabilistic early expiration (XFetch), mutex locking (single flight), or pre-computing hot keys.',
    evaluation_criteria: [
      'Accurately explains Cache-Aside flow and cache miss penalty',
      'Identifies the thundering herd problem when hot cache keys expire',
      'Proposes locking (Redis SETNX lock) or background jittered refresh to mitigate stampedes',
    ],
    difficulty: 3,
  },

  // ── Node.js & TypeScript & Asynchronous Runtimes ───────────────────────────
  {
    category: 'technical',
    tags: ['node.js', 'typescript', 'javascript', 'event loop', 'async', 'promises'],
    prompt: 'Explain the Node.js Event Loop phases and how microtasks (process.nextTick, Promise callbacks) differ from macrotasks (setTimeout, setImmediate).',
    answer_outline:
      'The libuv event loop has phases: Timers, Pending Callbacks, Idle/Prepare, Poll (I/O), Check (setImmediate), and Close Callbacks. Microtasks execute immediately after the current operation finishes and before moving to the next event loop phase, with process.nextTick having highest priority over Promise jobs.',
    evaluation_criteria: [
      'Details key event loop phases (Timers, Poll, Check)',
      'Explains that microtask queues drain fully between macrotasks and phase transitions',
      'Identifies starvation risks if recursive process.nextTick() calls block the loop',
    ],
    difficulty: 2,
  },
  {
    category: 'technical',
    tags: ['typescript', 'typing', 'generics', 'type-safety', 'interface'],
    prompt: 'How do TypeScript generics and conditional types enhance compile-time type safety without runtime overhead?',
    answer_outline:
      'Generics parameterize types to enable reusable components while preserving strict type relationships. Conditional types (T extends U ? X : Y) allow dynamic type mapping based on relationships, fully erased during transpilation so runtime bundle size is unaffected.',
    evaluation_criteria: [
      'Articulates compile-time type erasure in TypeScript',
      'Demonstrates understanding of generic constraints (extends keyword)',
      'Explains how utility types like Partial, Record, and Pick are constructed',
    ],
    difficulty: 2,
  },

  // ── Databases & Relational Storage ────────────────────────────────────────
  {
    category: 'technical',
    tags: ['database', 'sql', 'postgresql', 'mysql', 'indexing', 'transactions', 'acid'],
    prompt: 'How do B-Tree indexes improve SQL query performance, and what are the write penalties associated with maintaining multiple secondary indexes?',
    answer_outline:
      'B-Trees keep data sorted and allow logarithmic O(log n) lookups, range scans, and binary searches. The write penalty is that every INSERT, UPDATE (on indexed columns), and DELETE requires rebalancing and writing to multiple index trees, increasing I/O and transaction lock contention.',
    evaluation_criteria: [
      'Explains balanced tree traversal and page splits',
      'Discusses composite index column ordering (Leftmost Prefix Rule)',
      'Identifies index maintenance write overhead during high-volume ingestion',
    ],
    difficulty: 2,
  },

  // ── Cloud, Containers & Infrastructure ────────────────────────────────────
  {
    category: 'technical',
    tags: ['cloud', 'aws', 'docker', 'kubernetes', 'containers', 'infrastructure', 's3', 'lambda'],
    prompt: 'What are the architectural trade-offs between deploying microservices on serverless functions (e.g. AWS Lambda) vs container orchestration (e.g. Kubernetes/ECS)?',
    answer_outline:
      'Serverless provides zero-maintenance auto-scaling and per-millisecond billing, but suffers from cold starts, execution timeout limits (15 min), and statelessness. Containers provide predictable latency, local state/caching, long-running processes, and portability at the cost of infrastructure management and idle resource costs.',
    evaluation_criteria: [
      'Explains cold-start latency factors (VPC attachment, runtime bootstrap)',
      'Discusses cost dynamics: intermittent bursts (Lambda) vs steady high throughput (Containers)',
      'Considers observability, connection pooling (RDS Proxy), and networking constraints',
    ],
    difficulty: 2,
  },

  // ── Object-Oriented Design & Clean Architecture ───────────────────────────
  {
    category: 'technical',
    tags: ['oop', 'design patterns', 'solid', 'clean code', 'architecture'],
    prompt: 'Explain the Single Responsibility Principle and the Dependency Inversion Principle from SOLID. How do they prevent tight coupling?',
    answer_outline:
      'Single Responsibility dictates that a class or module should have only one reason to change. Dependency Inversion asserts that high-level business logic should depend on abstractions (interfaces) rather than concrete low-level implementations, allowing dependencies to be swapped or mocked in tests.',
    evaluation_criteria: [
      'Clear definition of SRP without confusing it with doing only one single thing',
      'Explains Dependency Inversion through interface contracts and inversion of control (IoC)',
      'Discusses practical testability benefits (mocking databases/network layers)',
    ],
    difficulty: 2,
  },

  // ── Behavioral & STAR Leadership Principles ───────────────────────────────
  {
    category: 'behavioural',
    tags: ['ownership', 'leadership', 'responsibility', 'initiative', 'proactive', 'culture', 'values'],
    prompt: 'Tell me about a time when you saw a problem or technical debt outside your direct project responsibility and took initiative to fix it.',
    answer_outline:
      'Use the STAR method: Describe the Context (e.g., recurring deployment flakiness impacting multiple teams), the Action you took (investigated root causes, proposed an automated health check, documented findings), and the measurable Result (reduced deployment failures by 40%).',
    evaluation_criteria: [
      'Clear STAR structure (Situation, Task, Action, Result)',
      'Demonstrates self-directed initiative without waiting to be assigned',
      'Highlights long-term team impact and quantifiable improvement',
    ],
    difficulty: 2,
  },
  {
    category: 'behavioural',
    tags: ['customer obsession', 'empathy', 'user-centric', 'feedback', 'culture', 'values'],
    prompt: 'Give an example of a time when you had to make a technical trade-off to prioritize customer experience or user trust over technical elegance.',
    answer_outline:
      'STAR approach: Explain a situation where a complex, elegant architectural refactor would have delayed a critical user security fix or degraded checkout latency. Emphasize how you chose a pragmatic, backward-compatible solution that protected user trust first.',
    evaluation_criteria: [
      'Demonstrates customer-first mindset over developer convenience',
      'Shows thoughtful balance between immediate user reliability and technical debt',
      'Details how follow-up refactoring was scheduled post-launch',
    ],
    difficulty: 2,
  },
  {
    category: 'behavioural',
    tags: ['collaboration', 'conflict', 'disagree and commit', 'teamwork', 'communication'],
    prompt: 'Describe a situation where you had a strong technical disagreement with a teammate or lead. How did you handle the conversation and reach a resolution?',
    answer_outline:
      'STAR approach: Detail the technical debate (e.g. database choice or API contract). Emphasize grounding the discussion in objective metrics, benchmarks, and data rather than ego. If the final decision went against your preference, demonstrate how you committed 100% to making the chosen solution succeed.',
    evaluation_criteria: [
      'Demonstrates professional, blameless communication',
      'Relies on data, benchmarks, and RFC trade-offs rather than opinions',
      'Shows maturity to "disagree and commit" and support the team outcome',
    ],
    difficulty: 2,
  },
  {
    category: 'behavioural',
    tags: ['failure', 'incident', 'postmortem', 'mistake', 'learning', 'resilience'],
    prompt: 'Tell me about a time you made a significant mistake or caused a production issue. What did you learn and what safeguards did you put in place?',
    answer_outline:
      'STAR approach: Take complete ownership of the incident without deflecting blame. Describe rapid containment/rollback, conducting a blameless postmortem, and implementing systemic safeguards (e.g. automated integration tests, canary deployments, alerting) so the issue could never recur.',
    evaluation_criteria: [
      'Takes unequivocal personal accountability',
      'Focuses on root cause analysis rather than defensiveness',
      'Implements systemic, automated prevention to protect future releases',
    ],
    difficulty: 2,
  },

  // ── Testing, Quality & CI/CD ──────────────────────────────────────────────
  {
    category: 'technical',
    tags: ['testing', 'unit tests', 'integration tests', 'ci/cd', 'quality', 'tdd'],
    prompt: 'How do you structure the testing pyramid (Unit, Integration, End-to-End) to ensure fast feedback loops without sacrificing confidence?',
    answer_outline:
      'The base consists of fast, hermetic unit tests verifying edge cases and business logic in isolation. The middle consists of integration tests verifying database queries, API schemas, and contracts against real ephemeral services. The top consists of minimal end-to-end smoke tests validating critical user flows.',
    evaluation_criteria: [
      'Understands test speed and cost trade-offs across pyramid tiers',
      'Emphasizes hermetic, deterministic execution (avoiding shared test state)',
      'Explains when to mock external third-party services vs test against real databases',
    ],
    difficulty: 1,
  },
];

export interface MatchedCuratedResult {
  questions: Question[];
  coveredRequirementIds: Set<string>;
  nextQuestionIndex: number;
}

/**
 * Matches candidate job requirements against the curated template bank using
 * semantic tag overlap, generating monotonic IDs and dynamically binding requirement IDs.
 */
export function matchCuratedQuestions(
  requirements: Requirement[],
  startIndex: number = 1,
  maxMatches: number = 4
): MatchedCuratedResult {
  const matchedQuestions: Question[] = [];
  const coveredRequirementIds = new Set<string>();
  const usedTemplatePrompts = new Set<string>();

  let nextQIndex = startIndex;

  for (const req of requirements) {
    if (matchedQuestions.length >= maxMatches) break;

    const reqTextLower = req.text.toLowerCase();
    const reqKind = req.kind;

    // Search for best matching template
    let bestTemplate: CuratedQuestionTemplate | null = null;
    let maxMatchScore = 0;

    for (const template of CURATED_QUESTION_TEMPLATES) {
      if (usedTemplatePrompts.has(template.prompt)) continue;

      // Category compatibility
      if (reqKind === 'behavioural' && template.category !== 'behavioural') continue;
      if (reqKind === 'technical' && template.category !== 'technical') continue;

      let score = 0;
      for (const tag of template.tags) {
        if (reqTextLower.includes(tag.toLowerCase())) {
          score += 1;
        }
      }

      if (score > maxMatchScore) {
        maxMatchScore = score;
        bestTemplate = template;
      }
    }

    // Only bind if there is a genuine keyword match (score >= 1)
    if (bestTemplate && maxMatchScore >= 1) {
      usedTemplatePrompts.add(bestTemplate.prompt);
      const qId = genQIds(1, nextQIndex - 1)[0];
      nextQIndex++;

      matchedQuestions.push({
        id: qId,
        requirement_ids: [req.id],
        category: bestTemplate.category,
        prompt: bestTemplate.prompt,
        answer_outline: bestTemplate.answer_outline,
        difficulty: bestTemplate.difficulty,
      });

      coveredRequirementIds.add(req.id);
    }
  }

  return {
    questions: matchedQuestions,
    coveredRequirementIds,
    nextQuestionIndex: nextQIndex,
  };
}
