/**
 * Domain 5 & 9: Interview Prep Kit Markdown Exporter
 * Generates an offline, beautifully formatted Markdown study guide.
 */
import { Kit } from '@taro/shared';

export function exportKitToMarkdown(kit: Kit, title?: string): string {
  const company = kit.source?.company || 'Company';
  const role = kit.source?.role || kit.role?.title || 'Role';
  const docTitle = title || `${role} at ${company} — Interview Prep Kit`;

  const lines: string[] = [
    `# ${docTitle}`,
    `> **Target Company**: [${company}](${kit.source?.company_url || '#'})  `,
    `> **Role**: ${role} (${kit.role?.seniority || 'Mid-Level'})  `,
    `> **Location**: ${kit.source?.location || 'Not specified'}  `,
    `> **Researched At**: ${kit.source?.researched_at || new Date().toISOString()}  `,
    `> **Preparation Window**: ${kit.schedule?.days_available || 5} Days`,
    '',
    '---',
    '',
    '## 1. Company Intelligence Brief',
    '',
    '### Summary',
    kit.company_brief?.summary || 'No summary available.',
    '',
    '### What They Do',
    kit.company_brief?.what_they_do || 'Information not specified.',
    '',
  ];

  if (kit.company_brief?.sources && kit.company_brief.sources.length > 0) {
    lines.push('### Sources Used');
    for (const src of kit.company_brief.sources) {
      lines.push(`- [${src}](${src})`);
    }
    lines.push('');
  }

  lines.push('---', '', '## 2. Job Description Requirements', '');
  if (kit.role?.responsibilities && kit.role.responsibilities.length > 0) {
    lines.push('### Core Responsibilities');
    for (const resp of kit.role.responsibilities) {
      lines.push(`- ${resp}`);
    }
    lines.push('');
  }

  lines.push('### Extracted Qualifications & Competencies');
  for (const req of kit.role?.requirements || []) {
    const badge = req.priority === 'must' ? '**[MUST-HAVE]**' : '*[Nice-to-Have]*';
    lines.push(`- **\`${req.id}\`** ${badge} (${req.kind}): ${req.text}`);
  }
  lines.push('');

  lines.push('---', '', '## 3. Targeted Question Bank', '');
  const categories = ['technical', 'system-design', 'behavioural', 'company-fit'] as const;
  for (const cat of categories) {
    const catQuestions = (kit.questions || []).filter((q) => q.category === cat);
    if (catQuestions.length === 0) continue;

    const catName = cat.charAt(0).toUpperCase() + cat.slice(1).replace('-', ' ');
    lines.push(`### ${catName} (${catQuestions.length} Questions)`, '');

    for (const q of catQuestions) {
      const diffStars = '★'.repeat(q.difficulty) + '☆'.repeat(3 - q.difficulty);
      lines.push(`#### [${q.id}] ${q.prompt}`);
      lines.push(`- **Difficulty**: Level ${q.difficulty} (${diffStars})`);
      lines.push(`- **Mapped Requirements**: ${q.requirement_ids.map((r) => `\`${r}\``).join(', ')}`);
      lines.push('', '##### Suggested Answer Outline & Discussion Rubric:', q.answer_outline, '');
    }
  }

  lines.push('---', '', '## 4. Rapid-Revision Flashcard Deck', '');
  for (const fc of kit.flashcards || []) {
    lines.push(`### [${fc.id}] ${fc.front}`);
    lines.push(`**Recall Outline**: ${fc.back}`);
    lines.push(`*Requirements*: ${fc.requirement_ids.map((r) => `\`${r}\``).join(', ')}`, '');
  }

  lines.push('---', '', '## 5. Day-by-Day Study Schedule', '');
  for (const day of kit.schedule?.days || []) {
    lines.push(`### Day ${day.day}: ${day.focus} (${day.minutes} Minutes)`);
    lines.push(
      `- **Questions**: ${
        day.question_ids.length > 0 ? day.question_ids.map((id) => `\`${id}\``).join(', ') : 'Self-directed review'
      }`
    );
    lines.push('');
  }

  lines.push('---', '', '*Generated by Recon AI Interview Prep Kit Engine.*');
  return lines.join('\n');
}
